### ISSUE TITLE
Fix pep8 errors in testing_modules

### ISSUE THREAD

**Issue by santhoshtr** [nandajavarma/Automated-Rendering-Testing#1]
testing_modules/**init**.py:2:31: W291 trailing whitespace
testing_modules/create_result.py:4:1: E302 expected 2 blank lines, found 0
testing_modules/create_result.py:5:3: E111 indentation is not a multiple of four
testing_modules/create_result.py:6:3: E111 indentation is not a multiple of four
testing_modules/create_result.py:7:3: E111 indentation is not a multiple of four
testing_modules/create_result.py:8:3: E111 indentation is not a multiple of four
testing_modules/create_result.py:10:8: E222 multiple spaces after operator
testing_modules/create_result.py:12:7: E111 indentation is not a multiple of four
testing_modules/create_result.py:17:7: E111 indentation is not a multiple of four
testing_modules/create_result.py:19:7: E111 indentation is not a multiple of four
testing_modules/create_result.py:21:17: E202 whitespace before ']'
testing_modules/create_result.py:22:7: E111 indentation is not a multiple of four
testing_modules/create_result.py:22:34: E225 missing whitespace around operator
testing_modules/create_result.py:24:7: E111 indentation is not a multiple of four
testing_modules/create_result.py:26:3: E111 indentation is not a multiple of four
testing_modules/create_result.py:27:3: E111 indentation is not a multiple of four
testing_modules/create_result.py:28:1: W391 blank line at end of file
testing_modules/test.py:3:1: E302 expected 2 blank lines, found 0
testing_modules/test.py:3:80: E501 line too long (87 > 79 characters)
testing_modules/test.py:4:3: E111 indentation is not a multiple of four
testing_modules/test.py:5:3: E111 indentation is not a multiple of four
testing_modules/test.py:6:3: E111 indentation is not a multiple of four
testing_modules/test.py:7:3: E111 indentation is not a multiple of four
testing_modules/test.py:9:3: E111 indentation is not a multiple of four
testing_modules/test.py:9:41: E231 missing whitespace after ','
testing_modules/test.py:9:57: E231 missing whitespace after ','
testing_modules/test.py:10:3: E111 indentation is not a multiple of four
testing_modules/test.py:11:3: E111 indentation is not a multiple of four
testing_modules/test.py:12:3: E111 indentation is not a multiple of four
testing_modules/test.py:13:3: E111 indentation is not a multiple of four
testing_modules/test.py:14:1: E101 indentation contains mixed spaces and tabs
testing_modules/test.py:14:1: W191 indentation contains tabs
testing_modules/test.py:15:3: E111 indentation is not a multiple of four
testing_modules/test.py:17:7: E111 indentation is not a multiple of four
testing_modules/test.py:18:7: E111 indentation is not a multiple of four
testing_modules/test.py:18:53: E261 at least two spaces before inline comment
testing_modules/test.py:18:54: E262 inline comment should start with '# '
testing_modules/test.py:18:80: E501 line too long (117 > 79 characters)
testing_modules/test.py:19:7: E111 indentation is not a multiple of four
testing_modules/test.py:20:7: E111 indentation is not a multiple of four
testing_modules/test.py:23:7: E111 indentation is not a multiple of four
testing_modules/test.py:23:49: E261 at least two spaces before inline comment
testing_modules/test.py:23:50: E262 inline comment should start with '# '
testing_modules/test.py:23:80: E501 line too long (149 > 79 characters)
testing_modules/test.py:26:1: E101 indentation contains mixed spaces and tabs
testing_modules/test.py:26:1: W191 indentation contains tabs
testing_modules/test.py:27:3: E111 indentation is not a multiple of four
testing_modules/test.py:27:41: E231 missing whitespace after ','
testing_modules/test.py:27:57: E231 missing whitespace after ','
testing_modules/test.py:28:3: E111 indentation is not a multiple of four
testing_modules/test.py:29:3: E111 indentation is not a multiple of four
testing_modules/test.py:32:3: E111 indentation is not a multiple of four
testing_modules/test.py:33:3: E111 indentation is not a multiple of four
testing_modules/test.py:36:7: E111 indentation is not a multiple of four
testing_modules/test.py:39:3: E111 indentation is not a multiple of four
testing_modules/test.py:40:3: E111 indentation is not a multiple of four
testing_modules/test.py:41:3: E111 indentation is not a multiple of four
testing_modules/test.py:43:3: E111 indentation is not a multiple of four
testing_modules/test.py:44:3: E111 indentation is not a multiple of four
testing_modules/test.py:45:3: E111 indentation is not a multiple of four
testing_modules/test.py:48:3: E111 indentation is not a multiple of four
testing_modules/test.py:51:80: E501 line too long (91 > 79 characters)
testing_modules/test.py:53:7: E111 indentation is not a multiple of four
testing_modules/test.py:54:7: E111 indentation is not a multiple of four
testing_modules/test.py:55:3: E111 indentation is not a multiple of four
testing_modules/test.py:57:3: E111 indentation is not a multiple of four
testing_modules/test.py:58:3: E111 indentation is not a multiple of four
testing_modules/test.py:59:3: E111 indentation is not a multiple of four
testing_modules/test.py:61:7: E111 indentation is not a multiple of four
testing_modules/test.py:65:7: E111 indentation is not a multiple of four
testing_modules/test.py:67:3: E111 indentation is not a multiple of four
testing_modules/test.py:68:43: E221 multiple spaces before operator
testing_modules/test.py:69:3: E111 indentation is not a multiple of four
testing_modules/test.py:70:1: E101 indentation contains mixed spaces and tabs
testing_modules/test.py:70:1: W191 indentation contains tabs
testing_modules/test.py:70:1: W293 blank line contains whitespace
testing_modules/test.py:70:1: W391 blank line at end of file

**Comment by nandajavarma** [comment]
The above mentioned commit fixes this issue.
