### ISSUE TITLE
Rachana- Wrong tests for Malayalam

### ISSUE THREAD

**Issue by santhoshtr** [nandajavarma/Automated-Rendering-Testing#19]
The following tests fails. But I dont see any issue in rendering. I guess tests are wrong. Please fix

എടാാാാാാാാ
ക്സ്ര
ന്റ്ര
ഖ്ര
ഥ്ര
വൎത്തുളം
പ്പ്ര
അൎജ്ജുനന്‍
യ‍്യ
വ‍്വ
ൎക്ക്ര
ഗ്ഗ്രോ
ഗ്ഗ്ര

Also, if test fails, instead of just showing red, we must show actual result and expected result(glyph sequencens. Otherwise it is not useful.

**Comment by santhoshtr** [comment]
same observed for Meera

**Comment by nandajavarma** [comment]
Commits 3e543e55d670b3f376fb08459972de9ef324f18d, 1993a2b14cef9f5f60239001417cb738990ece03 and ada7744c31496113e8d46f651a70a379ca48474b fixes this
