### ISSUE TITLE
Fix pep8 errors in rendering_testing.py

### ISSUE THREAD

**Issue by santhoshtr** [nandajavarma/Automated-Rendering-Testing#4]
rendering_testing.py:8:1: E302 expected 2 blank lines, found 0
rendering_testing.py:9:3: E111 indentation is not a multiple of four
rendering_testing.py:11:3: E111 indentation is not a multiple of four
rendering_testing.py:12:51: W291 trailing whitespace
rendering_testing.py:14:3: E111 indentation is not a multiple of four
rendering_testing.py:17:80: E501 line too long (125 > 79 characters)
rendering_testing.py:18:80: E501 line too long (139 > 79 characters)
rendering_testing.py:19:80: E501 line too long (148 > 79 characters)
rendering_testing.py:20:80: E501 line too long (109 > 79 characters)
rendering_testing.py:21:80: E501 line too long (118 > 79 characters)
rendering_testing.py:22:32: E251 unexpected spaces around keyword / parameter equals
rendering_testing.py:22:80: E501 line too long (108 > 79 characters)
rendering_testing.py:23:80: E501 line too long (137 > 79 characters)
rendering_testing.py:26:1: E101 indentation contains mixed spaces and tabs
rendering_testing.py:26:1: W191 indentation contains tabs
rendering_testing.py:28:1: E101 indentation contains mixed spaces and tabs
rendering_testing.py:28:1: W191 indentation contains tabs
rendering_testing.py:32:80: E501 line too long (135 > 79 characters)
rendering_testing.py:34:3: E111 indentation is not a multiple of four
rendering_testing.py:34:80: E501 line too long (188 > 79 characters)
rendering_testing.py:36:3: E111 indentation is not a multiple of four
rendering_testing.py:36:16: E231 missing whitespace after ','
rendering_testing.py:37:3: E111 indentation is not a multiple of four
rendering_testing.py:40:3: E111 indentation is not a multiple of four
rendering_testing.py:41:1: E101 indentation contains mixed spaces and tabs
rendering_testing.py:41:1: W191 indentation contains tabs
rendering_testing.py:42:3: E111 indentation is not a multiple of four
rendering_testing.py:46:7: E111 indentation is not a multiple of four
rendering_testing.py:46:13: E222 multiple spaces after operator
rendering_testing.py:46:80: E501 line too long (116 > 79 characters)
rendering_testing.py:47:7: E111 indentation is not a multiple of four
rendering_testing.py:48:80: E501 line too long (106 > 79 characters)
rendering_testing.py:55:1: W391 blank line at end of file

**Comment by nandajavarma** [comment]
The above commit fixes this issue.
