### ISSUE TITLE
webapp- main.css formatting is broken

### ISSUE THREAD

**Issue by santhoshtr** [nandajavarma/Automated-Rendering-Testing#6]
Use consistent whitespaces - use tabs for indentation. 

Use consistent  blank lines between style definitions.

body font:  font-family: ‘Palatino Linotype’, ‘Book Antiqua’, Palatino, serif; What are these fonts, are they used as webfonts?

background:#666666 url(img/button.png) no-repeat;
where is this image?

Use consistent spacing after column. clear:both; -> clear: both;

**Comment by nandajavarma** [comment]
This part of the code does not exist anymore.
