### ISSUE TITLE
HTML code issues

### ISSUE THREAD

**Issue by santhoshtr** [nandajavarma/Automated-Rendering-Testing#7]
Use consistent formatting. Do not mixup spaces and tabs.

Home.html - the div is not closed-  <div id="stylized" class="myform">

indentation is wrong.

<form action="" method=post id="form">
Some attributes has quotes, some does not have. same is the case for rest of the elements in home.html

Start using an IDE for editing code, then you will have consistent formatting and all the code issues can be identified easily.

layout.html has trailing whitespaces. 
It does not say page encoding.

what is the meaning of strong here
 <strong><link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"></strong>

**Comment by nandajavarma** [comment]
This part of the code does not exist anymore.
